# ----------
# rcicr code
# ----------
#
# NOTE: These lines of code are based on the rcicrdemo.R file pulled from the official website.
# The code should be modified as it is required.
#
# The script below shows how to analyze your data after stimuli have been generated and data has been collected
# using a 2IFC reverse correlation task.
# 
# The responses will be collected in responses.csv. The information about the presented stimuli that is used in the
# analysis is contained in workspace_data.Rdata. This file is automatically generated by rcicr when the stimuli are
# generated and contains a full archive of all stimulus parameters, including base image.
#
# For more information, please visit http://ron.dotsch.org/rcicr/. Subscribe to the user mailing list to stay
# up to date at http://lists.r-forge.r-project.org/pipermail/rcicr-users/. You can use this list to ask questions.
#
# ----------


# Load reverse correlation package ("rcicr")
library(rcicr)

# Base image name used during stimulus generation
# NOTE: retrieve base image name from 
baseimage <- 'base'

# File containing the contrast parameters (this file was created during stimulus generation)
rdata <- 'rcic_seed_1_time_Jul_22_2019_13_57.Rdata'

# Load response data
# NOTE: 'responses.csv' is used for general code; use appropriate names for each subject; see below
responsedata <- read.csv('responses.csv')

# change code as it is warranted
stimulus <- responsedata$stimulus
response <- responsedata$response

# Batch generate classification images by trait
cis <- generateCI(stimulus, response, baseimage, rdata)
# NOTES: change 'responsedata' as appropriate
 cis <- batchGenerateCI2IFC(responsedata, 'trait', 'stimulus', 'response', baseimage, rdata)

# NOTE: num_subjects not defined yet
# NOTE: using the for loop assumes subjects are numbered 1 through however-many subjects there are;
#       if ID numbers are used, the code should be changed as approriate
# for (i in 1:num_subjects){
#   responsedata_i <- read.csv(paste('responses', '_', i,'.csv', sep = ""));
#   ci_i <- batchGenerateCI2IFC(responsedata_i, 'trait', 'stimulus', 'response', baseimage, rdata)
# }

