# ----------
# rcicr code
# ----------
#
# NOTE: These lines of code are based on the rcicrdemo.R file pulled from the official website.
# The code should be modified as it is required.
#
# The script below shows how to analyze your data after stimuli have been generated and data has been collected
# using a 2IFC reverse correlation task.
# 
# The responses will be collected in responses.csv. The information about the presented stimuli that is used in the
# analysis is contained in workspace_data.Rdata. This file is automatically generated by rcicr when the stimuli are
# generated and contains a full archive of all stimulus parameters, including base image.
#
# For more information, please visit http://ron.dotsch.org/rcicr/. Subscribe to the user mailing list to stay
# up to date at http://lists.r-forge.r-project.org/pipermail/rcicr-users/. You can use this list to ask questions.
#
# ----------


# Load reverse correlation package ("rcicr")
library(rcicr)

# Base image name used during stimulus generation
baseimage <- 'base'

# File containing the contrast parameters (this file was created during stimulus generation)
# CHANGE 'workspace_data.Rdata' TO WHATEVER IS APPROPRIATE
rdata <- 'workspace_data.Rdata'

# Load response data
# CHANGE 'reponses.csv' TO WHATEVER IS APPROPRIATE
responsedata <- read.csv('responses.csv')

# Batch generate classification images by trait
cis <- batchGenerateCI2IFC(responsedata, 'trait', 'stimulus', 'response', baseimage, rdata)


